tasks:
  - name: setup-node
    before: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      nvm install 22
      nvm alias default 22
      nvm use 22
      corepack enable || true
    command: |
      npm ci
