image:
  file: .gitpod.Dockerfile
tasks:
  - name: EFH Autopilot
    init: |
      set -e
      npm ci || npm install
      sudo apt-get update -y
      sudo apt-get install -y ffmpeg jq
      pip install --user awscli || true
    command: |
      set -e
      chmod +x scripts/*.sh || true
      node scripts/env-check.js
      bash scripts/bootstrap.sh
