image:
  file: .gitpod.Dockerfile

# Prebuilds make the workspace open ready-to-run
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addBadge: false

# Expose common dev ports as PUBLIC (so preview works)
ports:
  - port: 3000
    visibility: public
    onOpen: open-preview
  - port: 5173
    visibility: public
    onOpen: open-preview
  - port: 8080
    visibility: public
    onOpen: open-preview

# One terminal runs the dev server with polling + proper host binding
tasks:
  - name: Boost FS watchers & run dev
    init: |
      chmod +x scripts/boost-watches.sh scripts/dev.sh
      ./scripts/boost-watches.sh
      corepack enable
      corepack prepare pnpm@9.7.0 --activate || true
      if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; elif [ -f package-lock.json ]; then npm ci; else npm i; fi
    command: |
      ./scripts/dev.sh

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
