image:
  file: .gitpod.Dockerfile

tasks:
  - name: EFH Auto-Clean & Setup
    init: |
      bash .gp/gitpod-start.sh --prebuild
    command: |
      bash .gp/gitpod-start.sh

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.vscode-json
    - bradlc.vscode-tailwindcss

# Speed up repo clones in future workspaces
gitConfig:
  core.autocrlf: input
  
# Ports for development servers
ports:
  - port: 3000
    onOpen: open-preview
    description: "Main development server"
  - port: 8080
    onOpen: open-preview
    description: "Alternative server"
  - port: 5173
    onOpen: open-preview
    description: "Vite dev server"
