workspaceClass: large

image:
  file: .gitpod.Dockerfile

ports:
  - port: 8012
    visibility: public
    onOpen: open-preview

tasks:
  - name: 🔥 Live Coding Environment
    init: |
      echo "🚀 Initializing Live Coding Environment..."
      corepack enable
      corepack prepare pnpm@9.7.0 --activate || true
      pnpm install --frozen-lockfile || pnpm install
      chmod +x scripts/*.sh
      chmod +x security/*.js
      npm install -g nodemon live-server
      echo "✅ Live coding dependencies installed"
    command: |
      echo "🔥 Starting Live Coding Server with Hot Reload..."
      scripts/live-coding-server.sh

  - name: 🤖 Autopilot Auto-Commit & Deploy
    command: |
      echo "🤖 Starting Autopilot Auto-Commit & Deploy System..."
      sleep 5  # Wait for live server to start
      scripts/autopilot-auto-commit-deploy.sh

  - name: 🛡️ Security & Monitoring
    command: |
      echo "🛡️ Activating security systems..."
      sleep 10  # Wait for other services
      scripts/autopilot-continuous-monitor.sh --auto-deploy

  - name: 📊 Development Dashboard
    command: |
      echo "📊 Starting development dashboard..."
      sleep 15  # Wait for all services
      scripts/dev-8012.sh

# Prebuilds for faster startup
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addBadge: false

# Essential VS Code extensions only
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode