# .gitpod.yml — Production preview in Gitpod
image: gitpod/workspace-node

# Optional: VS Code web extensions you'll probably want
vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss

# Tasks: setup Docker services and development environment
tasks:
  - name: Setup Environment
    init: |
      # Add Node.js to PATH
      export PATH="/usr/local/gitpod/shared/vscode/vscode-server/bin/6f17636121051a53c88d3e605c491d22af2ba755:$PATH"
      echo 'export PATH="/usr/local/gitpod/shared/vscode/vscode-server/bin/6f17636121051a53c88d3e605c491d22af2ba755:$PATH"' >> ~/.bashrc
      
      # Install dependencies
      npm ci || npm install --legacy-peer-deps || npm install --force
      
      # Build if needed
      npm run build || echo "Build not required for development"
    command: |
      # Start the development server
      export PATH="/usr/local/gitpod/shared/vscode/vscode-server/bin/6f17636121051a53c88d3e605c491d22af2ba755:$PATH"
      npm run dev

# Expose development ports
ports:
  - port: 5173
    onOpen: open-preview
    visibility: public
    description: "Vite Development Server"
  - port: 3000
    onOpen: ignore
    visibility: public
    description: "Deviate Backend Service"

# Optional: start tasks faster on subsequent opens
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true