image:
  file: .gitpod.Dockerfile

# Enterprise-ready deterministic setup
tasks:
  - name: Setup
    init: |
      # Lock Node version and package manager
      nvm install
      nvm use
      corepack enable
      corepack prepare pnpm@9.7.0 --activate
      
      # Install with frozen lockfile for deterministic builds
      pnpm install --frozen-lockfile
      
      # Pre-build for faster startup
      pnpm build
    command: |
      # Start development server
      pnpm dev

# Enable prebuilds for faster workspace startup
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addBadge: false

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.vscode-json
    - bradlc.vscode-tailwindcss
    - ms-vscode.vscode-typescript-next

# Enterprise Git configuration
gitConfig:
  core.autocrlf: input
  init.defaultBranch: main
  pull.rebase: false
  
# Development server ports
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
    description: "Main development server"
  - port: 3000
    onOpen: ignore
    description: "Alternative server"
  - port: 5173
    onOpen: ignore
    description: "Vite dev server"
  - port: 8001
    onOpen: ignore
    description: "Preview server"
