workspaceClass: large

image:
  file: .gitpod.Dockerfile

ports:
  - port: 8012
    visibility: public
    onOpen: open-preview

tasks:
  - name: Server (8012)
    init: |
      corepack enable
      corepack prepare pnpm@9.7.0 --activate || true
      pnpm install --frozen-lockfile || pnpm install
      chmod +x scripts/dev-8012.sh scripts/watchdog.sh scripts/healthcheck.sh scripts/autopilot.sh
    command: |
      # Run the server under the watchdog so it auto-restarts on crash
      scripts/watchdog.sh "scripts/dev-8012.sh"

  - name: Autopilot
    command: |
      # Independent health monitor that restarts if the port goes unhealthy
      scripts/autopilot.sh

# Prebuilds for faster startup
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addBadge: false

# Essential VS Code extensions only
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode