workspaceClass: large

image:
  file: .gitpod.Dockerfile

# Prebuilds make the workspace open ready-to-run
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addBadge: false

# Expose common dev ports as PUBLIC (so preview works)
ports:
  - port: 3000
    visibility: public
    onOpen: open-preview
  - port: 5173
    visibility: public
    onOpen: open-preview
  - port: 8080
    visibility: public
    onOpen: open-preview

# One terminal runs the dev server with native watchers (no polling)
tasks:
  - name: Dev
    init: |
      corepack enable
      corepack prepare pnpm@9.7.0 --activate || true
      pnpm install --frozen-lockfile || pnpm install
    command: |
      # use native watchers (no polling) to cut CPU
      HOST=0.0.0.0 WATCHPACK_POLLING=false CHOKIDAR_USEPOLLING=false pnpm dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
