# Netlify configuration for sister site
[build]
  publish = "."
  command = "echo 'Sister site deployed'"

# Custom domain configuration
[[redirects]]
  from = "https://selfishinc.org/*"
  to = "https://www.selfishinc.org/:splat"
  status = 301
  force = true

# Program redirects to main site
[[redirects]]
  from = "/programs/*"
  to = "https://elevateforhumanity.org/programs/:splat"
  status = 301

[[redirects]]
  from = "/apply"
  to = "https://elevateforhumanity.org/apply?source=selfishinc"
  status = 301

[[redirects]]
  from = "/student-portal"
  to = "https://elevateforhumanity.org/student-portal"
  status = 301

# Headers for sister site
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"