#!/usr/bin/env bash

echo "🚀 COMPLETE SETUP - READY TO DEPLOY"
echo "=================================="
echo ""
echo "✅ Your Wix DNS Values Found:"
echo "   A Record IP: 185.230.63.107"
echo "   CNAME Target: elevate4humanity.org"
echo ""
echo "🎯 DNS Records to Create in Cloudflare:"
echo ""
echo "1. A Record (Apex):"
echo "   Type: A"
echo "   Name: @"
echo "   Value: 185.230.63.107"
echo "   Proxy: OFF (Gray Cloud)"
echo ""
echo "2. CNAME Record (WWW):"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: elevate4humanity.org"
echo "   Proxy: OFF (Gray Cloud)"
echo ""
echo "📋 Manual Steps:"
echo "1. Go to Cloudflare Dashboard"
echo "2. Select elevateforhumanity.org zone"
echo "3. Go to DNS → Records"
echo "4. Create the two records above"
echo "5. Wait 5-10 minutes for propagation"
echo ""
echo "🧪 Test Commands:"
echo "curl -I https://elevateforhumanity.org"
echo "curl -I https://www.elevateforhumanity.org"
echo ""
echo "🎉 Result:"
echo "- elevateforhumanity.org → Wix site"
echo "- www.elevateforhumanity.org → Wix site"
echo ""
echo "📄 See COMPLETE_SETUP_MANUAL.md for detailed instructions"