#!/bin/bash
echo "🧪 Testing redirect chain for elevateforhumanity.org"
echo ""
echo "Expected behavior after fix:"
echo "1. http://elevateforhumanity.org → Cloudflare HTTPS → https://elevateforhumanity.org → _redirects → https://www.elevateforhumanity.org"
echo "2. https://elevateforhumanity.org → _redirects → https://www.elevateforhumanity.org"
echo "3. http://www.elevateforhumanity.org → Cloudflare HTTPS → https://www.elevateforhumanity.org"
echo "4. https://www.elevateforhumanity.org → Final destination (no redirect)"
echo ""
echo "✅ Redirect loop should be FIXED"
echo ""
echo "To test after deployment:"
echo "curl -I http://elevateforhumanity.org"
echo "curl -I https://elevateforhumanity.org"
echo "curl -I http://www.elevateforhumanity.org"
echo "curl -I https://www.elevateforhumanity.org"
