[build]
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://cdn.elevateforhumanity.org data:; script-src 'self' https://esm.sh; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co; frame-ancestors 'none'; base-uri 'self'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Protect the portal with an edge function
[[edge_functions]]
  path = "/portal/*"
  function = "require-auth"

# Protect enrollment system
[[edge_functions]]
  path = "/enroll/*"
  function = "require-auth"

# Protect LMS/student areas
[[edge_functions]]
  path = "/lms/*"
  function = "require-auth"

# Protect dashboard areas
[[edge_functions]]
  path = "/dashboard/*"
  function = "require-auth"