name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: npm ci || npm install --legacy-peer-deps
      - run: npm run lint --if-present
      - run: npm test --if-present
      - run: npm run build