name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main, fix/vercel-build-now, "copilot/**" ]
  workflow_dispatch: {}

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .npm
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Vite build
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.vite
            .vite
          key: ${{ runner.os }}-vite-${{ hashFiles('**/vite.config.js', '**/package-lock.json') }}

      - name: Install deps (fast mode)
        run: npm ci --prefer-offline --no-audit --progress=false || npm i --legacy-peer-deps --no-audit --progress=false

      - name: Build (optimized)
        run: npm run build
        env:
          NODE_ENV: production
          CI: true

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Prefer secrets, fallback to repo variables if present
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID || vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PAGES_PROJECT || vars.CLOUDFLARE_PAGES_PROJECT }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        
