name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
      skip_tests:
        description: 'Skip tests'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '20'
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.inputs.skip_tests != 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: |
        if [ -f "package.json" ] && npm run lint --if-present; then
          echo "✅ Linting passed"
        else
          echo "⚠️ No linting configured"
        fi

    - name: Run tests
      run: |
        if [ -f "package.json" ] && npm test --if-present; then
          echo "✅ Tests passed"
        else
          echo "⚠️ No tests configured"
        fi

    - name: Validate data files
      run: |
        echo "🔍 Validating data files..."
        
        # Check if all-programs.json exists and is valid
        if [ -f "data/seeds/all-programs.json" ]; then
          node -e "
            const fs = require('fs');
            try {
              const data = JSON.parse(fs.readFileSync('data/seeds/all-programs.json', 'utf8'));
              console.log('✅ all-programs.json is valid JSON');
              console.log('📊 Programs count:', Array.isArray(data) ? data.length : (data.programs ? data.programs.length : 'unknown'));
            } catch (error) {
              console.error('❌ all-programs.json is invalid:', error.message);
              process.exit(1);
            }
          "
        else
          echo "⚠️ all-programs.json not found"
        fi
        
        # Validate tenants.json
        if [ -f "tenants.json" ]; then
          node -e "
            const fs = require('fs');
            try {
              const data = JSON.parse(fs.readFileSync('tenants.json', 'utf8'));
              console.log('✅ tenants.json is valid JSON');
              console.log('📊 Tenants configured:', Object.keys(data).length);
            } catch (error) {
              console.error('❌ tenants.json is invalid:', error.message);
              process.exit(1);
            }
          "
        fi

  build:
    runs-on: ubuntu-latest
    needs: test
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Vite React app
      run: |
        if [ -d "vite-react-supabase-app" ]; then
          echo "🏗️ Building Vite React app..."
          cd vite-react-supabase-app
          npm ci
          npm run build
          cd ..
          echo "✅ Vite app built successfully"
        else
          echo "⚠️ No Vite app found"
        fi

    - name: Generate sitemaps
      run: |
        echo "🗺️ Generating sitemaps..."
        node scripts/generate-sitemap.js
      env:
        BASE_URL: 'https://www.elevateforhumanity.org'
        OUTPUT_DIR: './deploy'

    - name: Prepare deployment package
      run: |
        echo "📦 Preparing deployment package..."
        
        # Create deploy directory if it doesn't exist
        mkdir -p deploy
        
        # Copy static files
        if [ -d "public" ]; then
          cp -r public/* deploy/ 2>/dev/null || echo "No public files to copy"
        fi
        
        # Copy Vite build output
        if [ -d "vite-react-supabase-app/dist" ]; then
          cp -r vite-react-supabase-app/dist/* deploy/
          echo "✅ Copied Vite build output"
        fi
        
        # Copy Netlify configuration
        if [ -f "netlify.toml" ]; then
          cp netlify.toml deploy/
          echo "✅ Copied Netlify configuration"
        fi
        
        # Copy Netlify functions
        if [ -d "netlify/functions" ]; then
          mkdir -p deploy/netlify
          cp -r netlify/functions deploy/netlify/
          echo "✅ Copied Netlify functions"
        fi
        
        # Ensure _redirects file exists
        if [ ! -f "deploy/_redirects" ]; then
          echo "/* /index.html 200" > deploy/_redirects
          echo "✅ Created default _redirects file"
        fi
        
        echo "📁 Deployment package contents:"
        ls -la deploy/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: deploy/
        retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: deploy/

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      run: |
        echo "🚀 Deploying to Netlify..."
        
        if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
          # Deploy to staging
          netlify deploy --dir=deploy --site=${{ secrets.NETLIFY_STAGING_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
          echo "✅ Deployed to staging"
        else
          # Deploy to production
          netlify deploy --prod --dir=deploy --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
          echo "✅ Deployed to production"
        fi

    - name: Update Supabase Edge Functions
      run: |
        echo "🔄 Updating Supabase Edge Functions..."
        
        if [ -d "supabase/functions" ] && [ -n "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ]; then
          # Install Supabase CLI
          curl -sSfL https://supabase.com/install.sh | sh
          export PATH=$PATH:$HOME/.local/bin
          
          # Deploy Edge Functions
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          echo "✅ Edge Functions deployed"
        else
          echo "⚠️ Supabase functions not found or credentials missing"
        fi
      env:
        SUPABASE_ACCESS_TOKEN: sbp_v0_049f7f593a8093380bff6ae29f1afb41e4e71637

    - name: Notify deployment success
      run: |
        echo "🎉 Deployment completed successfully!"
        
        DEPLOY_URL="https://www.elevateforhumanity.org"
        if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
          DEPLOY_URL="https://staging.elevateforhumanity.org"
        fi
        
        echo "🌐 Site URL: $DEPLOY_URL"
        echo "📊 Commit: ${{ github.sha }}"
        echo "👤 Deployed by: ${{ github.actor }}"

    - name: Create deployment summary
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** ${{ github.event.inputs.environment || 'production' }}" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "**Deployed by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "**Deployed at:** $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        DEPLOY_URL="https://www.elevateforhumanity.org"
        if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
          DEPLOY_URL="https://staging.elevateforhumanity.org"
        fi
        
        echo "**Site URL:** [$DEPLOY_URL]($DEPLOY_URL)" >> $GITHUB_STEP_SUMMARY

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: [test, build, deploy]
    if: failure()
    
    steps:
    - name: Notify on failure
      run: |
        echo "❌ Deployment failed"
        echo "Failed jobs: ${{ toJson(needs) }}"
        # Add notification logic here (Slack, email, etc.)