name: Deploy Hub Pages to GitHub Pages

on:
  push:
    branches: [ main, master ]
    paths:
      - 'hub-pages/**'
      - '.github/workflows/deploy-hub-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare hub pages directory
        run: |
          # Use existing hub-pages directory with all files
          ls -la hub-pages/
          
          # Ensure CNAME file exists for custom domain
          echo "hubs.elevateforhumanity.org" > hub-pages/CNAME
          
          # Verify all required files exist
          echo "Checking hub pages files:"
          ls -la hub-pages/*.html
          
          # Create robots.txt if it doesn't exist
          if [ ! -f hub-pages/robots.txt ]; then
            echo "User-agent: *" > hub-pages/robots.txt
            echo "Allow: /" >> hub-pages/robots.txt
            echo "Sitemap: https://hubs.elevateforhumanity.org/sitemap.xml" >> hub-pages/robots.txt
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './hub-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4