name: Netlify Deploy Trigger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        env:
          NETLIFY_DEPLOY_HOOK_URL: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "${NETLIFY_DEPLOY_HOOK_URL:-}" ]; then
            echo "Missing secret NETLIFY_DEPLOY_HOOK_URL"; exit 1; fi
          curl -sS -X POST -H 'Content-Type: application/json' -d '{}' "$NETLIFY_DEPLOY_HOOK_URL"