name: Verify Cloudflare Secrets
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets exist
        run: |
          missing=0
          for v in CF_API_TOKEN CF_ACCOUNT_ID CF_ZONE_NAME CF_PAGES_PROJECT; do
            if [ -z "${{ secrets[v] }}" ]; then
              echo "❌ Missing secret: $v"; missing=1
            else
              echo "✅ Found: $v"
            fi
          done
          exit $missing
      - name: Install Wrangler
        run: npm i -g wrangler
      - name: Wrangler whoami (masked)
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          # 'wrangler whoami' uses env token if present
          wrangler whoami || { echo "Wrangler auth failed"; exit 1; }